### PR TITLE
Implements Oracle

### LINKED ISSUE #11: Add Oracle DBMS support

### PR DESCRIPTION
**Pull request by chaseWillden**
resolves #11 

Only annoying thing to keep in mind:

ODPI-C will need to be installed to communicate with the docker container:

https://odpi-c.readthedocs.io/en/latest/user_guide/installation.html#overview

### CODE REVIEW

**Comment by chaseWillden** [comment]
Looks like the build pipeline is failing. I'll get on that soonish

**Comment by mjovanc** [comment]
You are on fire Chase! I was going to look into this one but I'm happy you did! I am swamped at work 😂. Will u have time for Postgres after that? 😎

**Comment by chaseWillden** [comment]
> You are on fire Chase! I was going to look into this one but I'm happy you did! I am swamped at work 😂. Will u have time for Postgres after that? 😎

Yup I can knock that one out

**Comment by mjovanc** [comment]
Great work Chase!

**Comment by mjovanc** [comment]
@chaseWillden can I set the status as done for Oracle on the README and on the website?

**Pull request merged**
